services: mongodb
language: node_js
node_js:
  - "5.11"
addons:
    code_climate:
        repo_token: 9ee1095115f26eb40f5cc96e1d73020ae0e29f020ae731d22d048212cfaaa20
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info